apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  {{- with .Values.namespaceLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
