{{- range .Values.networkPolicies }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  {{- tpl (toYaml .spec) $ |  nindent 2 }}
{{- end }}
