{{- if .Values.registrySecret.dockerconfigjson }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  creationTimestamp: null
  namespace: {{ .Values.namespace }}
  name: {{ .Values.registrySecret.name }}
data:
  .dockerconfigjson: {{ .Values.registrySecret.dockerconfigjson }}
{{- end }}
