namespace: default-dev
namespaceLabels: {}
registrySecrets: []
# - name: container-registry
#   dockerconfigjson: null

# Deprecated. New versions will use registrySecrets instead of registrySecret
registrySecret:
  name: container-registry
  dockerconfigjson: null

networkPolicies: {}
  #  - name: allow-namespace-ingress-traffic
  #    spec:
  #      podSelector: {}
  #      ingress:
  #        - from:
  #            - namespaceSelector:
  #                matchLabels:
  #                  kubernetes.io/metadata.name: "{{ .Values.namespace }}"
  #  - name: default-deny-egress-traffic
  #    spec:
  #      podSelector: {}
  #      policyTypes:
  #        - Egress
  #  - name: allow-dns-egress-traffic
  #    spec:
  #      podSelector: {}
  #      policyTypes:
  #        - Egress
  #      egress:
  #        - to:
  #          - namespaceSelector:
  #              matchLabels:
  #                name: kube-system
  #          ports:
  #          - protocol: UDP
  #            port: 53
  #          - protocol: UDP
  #            port: 1053

quota:
  enabled: true
  requests:
    cpu: "1"
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi
  pods: "10"
  persistentvolumeclaims: "20"
  resourcequotas: "1"
  services: "5"

limits:
  enabled: true
  default:
    memory: 512Mi
  defaultRequest:
    cpu: 100m
    memory: 256Mi
  type: Container

# -- Array of extra K8s manifests to deploy
## Note: Supports use of custom Helm templates, when string value is provided.
extraManifests:
  []
  # For example, a Schedule for daily Velero backups
  ## https://velero.io/docs/v1.11/api-types/schedule/
  # - |
  #   apiVersion: velero.io/v1
  #   kind: Schedule
  #   metadata:
  #     name: {{ $.Values.namespace }}-daily
  #     namespace: velero
  #   spec:
  #     schedule: 0 3 * * 1-6
  #     template:
  #       csiSnapshotTimeout: 0s
  #       includedNamespaces:
  #         - {{ $.Values.namespace }}
  #       itemOperationTimeout: 0s
  #       snapshotVolumes: false
  #       ttl: 168h0m0s
  #     useOwnerReferencesInBackup: false
  #     paused: false
