namespace: default-dev
cluster: 
  name: in-cluster
  nameSuffix: ''
  address: https://kubernetes.default.svc
  ignoreClusterName: false

argo:
  namespace: argocd
  clusterResourceWhitelist: {}
  clusterResourceBlacklist: {}
  namespaceResourceBlacklist: {}
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  readOnlyGroups: []
  adminGroups: []
  repositories: []
    #  - name:
    #    username:
    #    password:
    #    url:
  baseApplication:
    projectName: default
    repoURL: https://mikroways.github.io/argo-gitops-flow
    path: null
    chart: argo-base-app
    targetRevision: 1.1.*
    helm: {}
    syncPolicy: {}
  applicationRequirements:
    enabled: false
    repoURL: null
    path: null
    chart: null
    targetRevision: null
    helm: {}
    syncPolicy: {}
  application:
    enabled: false
    sources: null
      # array of sources
    source: null
      #      repoURL: null
      #      path: null
      #      chart: null
      #      targetRevision: null
      #      helm: {}
      #      syncPolicy: {}
