namespace: default-dev
cluster: 
  name: in-cluster
  nameSuffix: ''
  address: https://kubernetes.default.svc

argo:
  namespace: argocd
  readOnlyGroups: []
  adminGroups: []
  repositories: []
    #  - name:
    #    username:
    #    password:
    #    url:
  baseApplication:
    projectName: default
    repoURL: https://mikroways.github.io/argo-gitops-flow
    path: null
    chart: argo-base-app
    targetRevision: 1.0.*
    helm: {}
    syncPolicy: {}
  applicationRequirements:
    enabled: false
    repoURL: null
    path: null
    chart: null
    targetRevision: null
    helm: {}
    syncPolicy: {}
  application:
    enabled: false
    repoURL: null
    path: null
    chart: null
    targetRevision: null
    helm: {}
    syncPolicy: {}
