namespace: my-project
cluster: 
  name: testing

argo:
  readOnlyGroups:
    - exampleADgroupRO
  adminGroups:
    - exampleADAdmin
  extraDestinations:
    - extra-namespace
    - another-namespace
  repositories:
    - name: my-repo
      url: htts://a-url.repo.com/project/app
      username: user_a
      password: secret-pass
  applicationRequirements:
    enabled: true
    source:
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 11.3.x
      chart: mariadb
      helm:
        values: |
          auth:
            rootPassword: rootpass
            database: my-app-db
            username: user
            password: supersecret
  application:
    enabled: true
    sources:
      - repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: prometheus
        targetRevision: 15.7.1
        helm:
          valueFiles:
          - $values/charts/prometheus/values.yaml
      - repoURL: 'https://git.example.com/org/value-files.git'
        targetRevision: dev
        ref: values


